"""Alembic migration template."""
"""Auto-generated by Alembic - %{rev%}"""

revision = %{current_rev%}
down_revision = %{down_revision%}
branch_labels = %{branch_labels%}
depends_on = %{depends_on%}


def upgrade() -> None:
    %{upgrade%}


def downgrade() -> None:
    %{downgrade%}